### ISSUE TITLE
ELSE resets could have converted to THEN in zone files

### ISSUE THREAD

**Issue by rabidt** [LuminariMUD/Luminari-Source#13]
Due to change in 016ba8b597d04cdd6652e3a3fbd127741828247b , ELSE resets were being treated as THEN, and if a zone was saved during that time (before fix in 867b019ace24845d7baf33081d398a7c90ce94f2), the resets would have been saved as THEN in the zone file.

**Comment by moshehbenavraham** [comment]
Unfortunately will have to close this issue because we have no backups and will just have to brute force address these issues as we audit zones

**Comment by Bobsson** [comment]
I have a full backup of everything from the server move last June.  It won't help with anything that has been changed since then, but for any untouched zones, it may be useful.
