### ISSUE TITLE
 How do I compile for testing?

### ISSUE THREAD

**Issue by CryAngel1970** [LuminariMUD/Luminari-Source#23]
I am studying C language by compiling TbaMud in MSVC 2019.

I accidentally found this mud source and tried to compile it, but an error occurred and was unsuccessful.
My test environment is Windows 10 and I can compile MSVC and GCC.

**Comment by moshehbenavraham** [comment]
> I am studying C language by compiling TbaMud in MSVC 2019.
> 
> I accidentally found this mud source and tried to compile it, but an error occurred and was unsuccessful.
> My test environment is Windows 10 and I can compile MSVC and GCC.

Honestly nobody has ever bothered to update the code for windows compatibility (unfortunately)...
