### ISSUE TITLE
Compiling Ubuntu on WSL2 on Windows 10

### ISSUE THREAD

**Issue by CryAngel1970** [LuminariMUD/Luminari-Source#34]
I am using Windows 10 and installed Ubuntu using wsl.
And, I installed gcc, make, and mysql.
I installed VS Code on Windows 10.

Can I get a step-by-step manual for compiling Luminari-Source in this environment?

**Comment by moshehbenavraham** [comment]
I'm not sure if anyone active has done that particular installation.  If you join the Discord server, one of the Forgers has successfully installed it twice on (I believe) Linux environments (or similar) and may be able to support (no promises).

**Comment by CryAngel1970** [comment]
Thank you for your reply, @moshehbenavraham.

I'm not good at English, so I'm using Google Translate now.
So, I am not confident in real-time English conversation.

I installed Ubuntu via WSL2 after reading that it was difficult to compile on Windows.
I've only used Windows, so this is my first time using Linux.

Make did not proceed because campaign.h was missing during compilation.

I read the description of campaign.h in structs.h file.
I installed git repo.
But I still get an error.

It seems that the version that continues to develop TbaMUD is LuminariMUD, so I tried to use LuminariMUD, but there are many difficulties.

Thanks for reading.

**Comment by moshehbenavraham** [comment]
You are welcome, do not stress about the language barrier.  LuminariMUD was built on TbaMUD, but is not a continuation.  It is a very different branch.  It is an attempt to adapt the Pathfinder Open-Gaming ruleset along with some custom rules.  The code has tens of thousands of changes from TbaMUD.  Using TbaMUD would be much easier code to install.

The only support we might be able to offer is if you join our Discord server and ask on the "#codebase-talk" channel.  As far as I know, only @GickerLDS actively develops another version of LuminariMUD.
